'use client';

import { useEffect, useRef, useState } from 'react';
import s from './prototype.module.css';

const templates = ['Lịch trình Note theo giờ', 'Lịch trình Note 2 ngày', 'Spotlight Nhật ký Đà Lạt', 'Spotlight V6 Google Maps'];
const initialRows = Array.from({ length: 8 }, (_, i) => ({ time: ['07:00–07:45','08:15–09:15','10:00–11:15','11:15–12:15','14:15–15:30','16:00–17:15','17:30–19:00','19:00–21:00'][i], name: `Địa điểm minh họa ${i + 1}`, address: `${12 + i} Địa chỉ minh họa, Đà Lạt` }));
const fixtureLists = Array.from({length:12}, (_, i) => ({ id:i+1, name:`Đà Lạt cuối tuần · ${String(i+1).padStart(2,'0')}`, template:templates[i%4], pages:i%4<2?2:10 }));

export default function Prototype() {
  const [theme,setTheme]=useState('dark'), [ready,setReady]=useState(false);
  const [view,setView]=useState('Làm bài'), [step,setStep]=useState(2), [mobile,setMobile]=useState('preview');
  const [chosen,setChosen]=useState(templates[0]), [search,setSearch]=useState(''), [filter,setFilter]=useState('Tất cả');
  const [rows,setRows]=useState(initialRows), [saved,setSaved]=useState(initialRows), [day,setDay]=useState(1), [dirty,setDirty]=useState(false);
  const [selected,setSelected]=useState([]), [notice,setNotice]=useState('Dữ liệu giả · Không kết nối backend hoặc Google Sheet.');
  const [modal,setModal]=useState(false), [exportStep,setExportStep]=useState(0), [quality,setQuality]=useState('Cân bằng');
  const [scheduleTab,setScheduleTab]=useState('Tạo lịch'), [scheduleName,setScheduleName]=useState(''), [scheduleMade,setScheduleMade]=useState(false);
  const [quantity,setQuantity]=useState(3), [history,setHistory]=useState(true);
  const dialog=useRef(null), returnFocus=useRef(null);
  useEffect(()=>{setTheme(localStorage.getItem('dalat-ui-prototype-theme') || (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));setReady(true);},[]);
  useEffect(()=>{if(ready)localStorage.setItem('dalat-ui-prototype-theme',theme);},[theme,ready]);
  useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  useEffect(()=>{if(!modal)return;returnFocus.current=document.activeElement;dialog.current?.querySelector('button')?.focus();return()=>returnFocus.current?.focus();},[modal]);
  const leave=(action)=>{if(!dirty||window.confirm('Bạn có thay đổi chưa lưu. Bỏ thay đổi để chuyển màn hình?')){setRows(saved);setDirty(false);action();}};
  const navigate=next=>leave(()=>{setView(next);setSearch('');setFilter('Tất cả');});
  const edit=(i,key,value)=>{setRows(rows.map((r,j)=>i===j?{...r,[key]:value}:r));setDirty(true);};
  const toggle=id=>setSelected(selected.includes(id)?selected.filter(n=>n!==id):[...selected,id]);
  const filtered=fixtureLists.filter(l=>(filter==='Tất cả'||l.template===filter)&&`${l.name} ${l.template}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
  const openExport=()=>{setExportStep(0);setModal(true);};
  const totalPages=fixtureLists.filter(l=>selected.includes(l.id)).reduce((n,l)=>n+l.pages,0);
  return <main className={s.root} data-theme={theme} style={{visibility:ready?'visible':'hidden'}}>
    <aside className={s.sidebar}><div className={s.brand}><b>ĐL</b><span>Dalat Studio<small>Không gian sáng tạo</small></span></div>
      <p className={s.eyebrow}>WORKSPACE</p><nav aria-label="Điều hướng prototype">{['Làm bài','List đã tạo','Hẹn giờ','Dữ liệu & Cài đặt'].map((v,i)=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>navigate(v)}><span>{['✦','▤','◷','⚙'][i]}</span>{v}</button>)}</nav>
      <div className={s.sidebarBottom}><span className={s.pill}>Bản thiết kế thử</span><p>Không tạo list hay file thật.</p><a href="/">← Về tool hiện tại</a></div></aside>
    <section className={s.workspace}><header className={s.header}><div><p className={s.eyebrow}>ĐÀ LẠT / STUDIO</p><h1>{view}</h1></div><div className={s.headerActions}><span className={s.pill}>● Dữ liệu minh họa</span><button onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Đổi giao diện sáng tối">{theme==='dark'?'☀ Sáng':'☾ Tối'}</button></div></header>
      <div className={s.notice} role="status">{notice}</div>
      {view==='Làm bài'&&<>
        <div className={s.steps}>{['Chọn mẫu','Tạo list','Chỉnh sửa','Xuất file'].map((label,i)=><button key={label} className={step===i?s.active:''} onClick={()=>leave(()=>{if(i===3){setSelected([1]);openExport();}else setStep(i);})}><span>{i+1}</span>{label}</button>)}</div>
        {step===0&&<section className={s.content}><div className={s.sectionHead}><div><h2>Chọn cách kể câu chuyện</h2><p>Mẫu Note cho Threads, Spotlight và lịch trình cho TikTok.</p></div></div><input aria-label="Tìm mẫu" placeholder="Tìm tên mẫu…" value={search} onChange={e=>setSearch(e.target.value)}/><div className={s.cards}>{templates.filter(t=>t.toLowerCase().includes(search.toLowerCase())).map((t,i)=><button className={s.template} key={t} onClick={()=>{setChosen(t);setStep(1);}}><div className={s.art}>{i<2?'☷':'✦'}<small>{i<2?'GHI CHÚ CHUYẾN ĐI':'ĐÀ LẠT / SPOTLIGHT'}</small></div><strong>{t}</strong><p>{i<2?'9:16 · 2 trang':'3:4 · 10–14 trang'} · Xem mẫu →</p></button>)}</div></section>}
        {step===1&&<section className={`${s.content} ${s.form}`}><p className={s.eyebrow}>MẪU ĐÃ CHỌN</p><h2>{chosen}</h2><label>Số list<input type="number" min="1" max="10" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Nguồn hook<select disabled={chosen.includes('Note')}><option>{chosen.includes('Note')?'Mẫu Note không dùng hook':'Hook thường'}</option></select></label><p>Mỗi list chọn địa điểm mới. Không sao chép dữ liệu từ mẫu mẹ.</p><button className={s.primary} disabled={quantity<1||quantity>10} onClick={()=>{setStep(2);setNotice('Mô phỏng tạo list hoàn tất. Đây vẫn là dữ liệu giả.');}}>Tạo {quantity} list · mô phỏng</button></section>}
        {step===2&&<><div className={s.sectionHead}><div><h2>{chosen}</h2><p>Mẫu mẹ · Ngày {day} · Thay đổi chỉ trong prototype</p></div><span className={s.pill}>{dirty?'● Chưa lưu':'✓ Đã lưu'}</span></div>
          <div className={s.mobileTabs}><button onClick={()=>setMobile('preview')}>Xem preview</button><button onClick={()=>setMobile('editor')}>Chỉnh sửa</button></div>
          <div className={s.editorGrid} data-pane={mobile}><aside className={s.pages}><h3>Trang trong list</h3>{[1,2].map(d=><button key={d} className={day===d?s.active:''} onClick={()=>leave(()=>setDay(d))}><b>0{d}</b><span>🌷 Ngày {d}<small>{d===1?'8 hoạt động':'5 hoạt động + 2 dòng cố định'}</small></span></button>)}</aside>
            <section className={s.preview}><div className={s.previewMeta}><span>PREVIEW MINH HỌA</span><span>9:16</span></div><div className={s.paper}><div className={s.phone}><b>09:41</b><span>▮▮ ▰ 48%</span></div><div className={s.noteNav}>‹ Tất cả iCloud <span>↥ ⋯</span></div><p className={s.date}>09:41 ngày 16 tháng 9, 2026</p><h3>🌷 Ngày {day}</h3>{rows.slice(0,day===1?8:5).map((r,i)=><div key={i} className={s.noteRow}><u>{r.time}</u><p>{i%2?'☕':'📍'} {r.name}{r.address?` – ${r.address}`:''}</p></div>)}<footer>☷ <span>▣</span> ♧ <span>□</span></footer></div><p>Preview bố cục UI; không thay renderer ảnh thật.</p></section>
            <section className={s.editor}><div className={s.panelHead}><h3>Dữ liệu & nội dung</h3><p>Ngày {day} · mỗi hoạt động một địa điểm</p></div><div className={s.fields}>{rows.slice(0,day===1?8:5).map((r,i)=><fieldset key={i}><legend>Hoạt động {i+1}</legend><label>Khung giờ<input value={r.time} onChange={e=>edit(i,'time',e.target.value)}/></label><label>Tên địa điểm<input value={r.name} onChange={e=>edit(i,'name',e.target.value)}/></label><label>Địa chỉ<textarea rows={2} value={r.address} onChange={e=>edit(i,'address',e.target.value)}/></label></fieldset>)}</div><div className={s.savebar}><span>{dirty?'Có thay đổi chưa lưu':'Đã lưu trong bản thử'}</span><button className={s.primary} onClick={()=>{setSaved(rows.map(r=>({...r})));setDirty(false);setNotice('Đã lưu nội dung minh họa trong phiên prototype.');}}>Lưu thay đổi</button></div></section>
          </div></>}
      </>}
      {view==='List đã tạo'&&<section className={s.content}><div className={s.sectionHead}><div><h2>Bài viết sẵn sàng của bạn</h2><p>12 list minh họa · quản lý và xuất tại một nơi</p></div><button className={s.primary} onClick={()=>navigate('Làm bài')}>+ Tạo list</button></div><div className={s.filters}><input aria-label="Tìm list" placeholder="Tìm tên list hoặc mẫu…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Lọc mẫu" value={filter} onChange={e=>setFilter(e.target.value)}>{['Tất cả',...templates].map(t=><option key={t}>{t}</option>)}</select></div><div className={s.selection}><span>{selected.length} list · {totalPages} trang đã chọn</span><button disabled={!selected.length} className={s.primary} onClick={openExport}>Xuất file →</button></div><div className={s.listRows}>{filtered.map(l=><label className={s.listRow} key={l.id}><input type="checkbox" checked={selected.includes(l.id)} onChange={()=>toggle(l.id)}/><b className={s.listIcon}>☷</b><span><strong>{l.name}</strong><small>{l.template} · {l.pages} trang</small></span><button type="button" onClick={()=>{setChosen(l.template);navigate('Làm bài');setStep(2);}}>Chỉnh sửa</button></label>)}{!filtered.length&&<p>Không tìm thấy list. Thử từ khóa khác.</p>}</div></section>}
      {view==='Hẹn giờ'&&<section className={s.content}><div className={s.sectionHead}><div><h2>Lên lịch, để Studio chuẩn bị</h2><p>Giờ Việt Nam · Tool cần đang mở · Xử lý lần lượt để giảm tải máy</p></div><span className={s.pill}>Thử nghiệm</span></div><div className={s.steps}>{['Tạo lịch','Lịch đã lưu','Hàng đợi & lịch sử'].map(t=><button className={scheduleTab===t?s.active:''} key={t} onClick={()=>setScheduleTab(t)}>{t}</button>)}</div>
        {scheduleTab==='Tạo lịch'?<div className={s.form}><label>Tên lịch<input placeholder="Ví dụ: Bài đăng buổi sáng" value={scheduleName} onChange={e=>setScheduleName(e.target.value)}/></label><div className={s.filters}><label>Destination<select><option>Đà Lạt</option><option>Green Land</option></select></label><label>Kiểu lịch<select><option>Một lần</option><option>Hằng ngày</option></select></label></div><label>Giờ bắt đầu<input type="datetime-local" defaultValue="2026-09-17T08:30"/></label><label>Nơi lưu ZIP<div className={s.selection}><span>Thư mục minh họa / Bài đăng</span><button onClick={()=>setNotice('Prototype không mở hộp thoại Windows; khi tích hợp sẽ dùng bộ chọn file hiện có.')}>Chọn nơi lưu</button></div></label><label>Mẫu<select>{templates.map(t=><option key={t}>{t}</option>)}</select></label><label>Số list cho mẫu<input type="number" min="3" max="5" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><p>{!scheduleName.trim()?'Nhập tên lịch để tiếp tục.':quantity<3||quantity>5?'Mỗi mẫu cần từ 3 đến 5 list.':`${quantity} list · Hook theo quy tắc của mẫu`}</p><button className={s.primary} disabled={!scheduleName.trim()||quantity<3||quantity>5} onClick={()=>{setScheduleMade(true);setScheduleTab('Lịch đã lưu');}}>Lưu lịch minh họa</button></div>:scheduleTab==='Lịch đã lưu'?<div className={s.scheduleCard}><h3>{scheduleMade?scheduleName:'Lịch buổi sáng · ví dụ'}</h3><p>Đà Lạt · Lịch trình Note theo giờ ×3</p><p>08:30 · Giờ bắt đầu, không phải giờ hoàn tất</p><button onClick={()=>setNotice('Mô phỏng: đã xếp lịch vào hàng đợi. Không chạy tác vụ thật.')}>Chạy ngay · mô phỏng</button></div>:<><div className={s.scheduleCard}><span className={s.pill}>Đang chờ · ví dụ</span><h3>Yêu cầu thủ công · 3 list</h3><p>Chờ lượt hiện tại kết thúc. Không chạy hai tác vụ nặng cùng lúc.</p><button onClick={()=>setNotice('Đã hủy yêu cầu minh họa.')}>Hủy yêu cầu</button></div>{history&&<div className={s.scheduleCard}><span className={s.pill}>✓ Hoàn tất · ví dụ</span><h3>Lịch hôm qua</h3><p>3 list · File ZIP đã lưu (dữ liệu minh họa)</p><button onClick={()=>{if(confirm('Xóa bản ghi minh họa? Không xóa ZIP hoặc list.'))setHistory(false);}}>Xóa lịch sử</button></div>}</>}
      </section>}
      {view==='Dữ liệu & Cài đặt'&&<section className={s.content}><h2>Dữ liệu & Cài đặt</h2><p>Màn hình này sẽ tích hợp sau khi ba màn hình chính được duyệt.</p><div className={s.cards}>{['Nguồn dữ liệu','Hook','Cache ảnh','Giao diện'].map(t=><div className={s.scheduleCard} key={t}><h3>{t}</h3><p>Giữ chức năng hiện có; không tự đồng bộ khi chuyển màn hình.</p></div>)}</div></section>}
    </section>
    {modal&&<div className={s.backdrop} onClick={e=>{if(e.target===e.currentTarget)setModal(false);}}><section className={s.dialog} ref={dialog} role="dialog" aria-modal="true" aria-labelledby="prototype-export-title" onKeyDown={e=>{if(e.key==='Escape')setModal(false);if(e.key==='Tab'){const nodes=[...dialog.current.querySelectorAll('button:not(:disabled),input,select')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><header className={s.sectionHead}><div><p className={s.eyebrow}>XUẤT FILE · BƯỚC {exportStep+1}/3</p><h2 id="prototype-export-title">{['List đã chọn','Chất lượng xuất','Xác nhận xuất'][exportStep]}</h2></div><button aria-label="Đóng xuất file" onClick={()=>setModal(false)}>✕</button></header><div className={s.dialogBody}>{exportStep===0?<><h3>{selected.length} list · {totalPages} trang</h3>{fixtureLists.filter(l=>selected.includes(l.id)).map(l=><p key={l.id}>{l.name} — {l.pages} trang</p>)}</>:exportStep===1?<>{['Cân bằng','Gốc'].map(q=><label className={s.scheduleCard} key={q}><input type="radio" name="prototype-quality" checked={quality===q} onChange={()=>setQuality(q)}/> <strong>{q}</strong><p>{q==='Cân bằng'?'Tự chọn chế độ phù hợp sức máy.':'Ảnh gốc; có thể cần nhiều thời gian và bộ nhớ.'}</p></label>)}</>:<><h3>{selected.length} list · {totalPages} trang · {quality}</h3><p>Prototype không tạo hoặc tải file thật.</p><label><input type="checkbox"/> Xóa list sau khi xuất thành công (minh họa)</label></>}</div><footer className={s.selection}><button disabled={exportStep===0} onClick={()=>setExportStep(exportStep-1)}>Quay lại</button><button className={s.primary} onClick={()=>{if(exportStep<2)setExportStep(exportStep+1);else{setModal(false);setNotice('Đã hoàn tất mô phỏng xuất. Không tạo file hoặc xóa list.');}}}>{exportStep<2?'Tiếp tục →':'Xác nhận · mô phỏng'}</button></footer></section></div>}
  </main>;
}
