server {
    listen 80;
    server_name 113.161.254.76;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/dalat-studio-updates;
        default_type text/plain;
        try_files $uri =404;
    }

    location / { return 404; }
}
