const fs = require('node:fs');
const path = require('node:path');

const rootDir = path.resolve(__dirname, '..');
const versionPath = path.join(rootDir, 'VERSION');
const packagePaths = [
  path.join(rootDir, 'package.json'),
  path.join(rootDir, 'frontend', 'package.json'),
  path.join(rootDir, 'backend', 'package.json'),
];
const appVersionPath = path.join(rootDir, 'frontend', 'lib', 'appVersion.js');
const MAX_PATCH = 10;

function parseVersion(raw) {
  const match = String(raw).trim().match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) {
    throw new Error(`VERSION must use major.minor.patch (x.y.z), got "${raw}"`);
  }
  const major = Number(match[1]);
  const minor = Number(match[2]);
  const patch = Number(match[3]);
  if (!Number.isInteger(major) || !Number.isInteger(minor) || !Number.isInteger(patch)) {
    throw new Error(`VERSION must use integers, got "${raw}"`);
  }
  if (patch < 1 || patch > MAX_PATCH) {
    throw new Error(`Patch must be between 1 and ${MAX_PATCH}, got "${raw}"`);
  }
  return { major, minor, patch };
}

function formatVersion(parts) {
  return `${parts.major}.${parts.minor}.${String(parts.patch).padStart(2, '0')}`;
}

function bumpVersion(parts) {
  if (parts.patch >= MAX_PATCH) {
    return { major: parts.major, minor: parts.minor + 1, patch: 1 };
  }
  return { ...parts, patch: parts.patch + 1 };
}

function readVersionParts() {
  return parseVersion(fs.readFileSync(versionPath, 'utf8'));
}

function writeVersionParts(parts) {
  fs.writeFileSync(versionPath, `${parts.major}.${parts.minor}.${parts.patch}\n`, 'utf8');
}

function updatePackageVersion(filePath, version) {
  const payload = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  payload.version = version;
  fs.writeFileSync(filePath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
}

function writeAppVersionModule(version) {
  const contents = `// Auto-generated by scripts/sync-version.js — do not edit manually.
// Patch 01-10 mỗi minor; sau .10 chuyển sang minor kế tiếp (.01).
export const APP_VERSION = '${version}';
`;
  fs.mkdirSync(path.dirname(appVersionPath), { recursive: true });
  fs.writeFileSync(appVersionPath, contents, 'utf8');
}

function syncVersion() {
  const parts = readVersionParts();
  const version = formatVersion(parts);
  for (const filePath of packagePaths) {
    updatePackageVersion(filePath, version);
  }
  writeAppVersionModule(version);
  return { parts, version };
}

if (require.main === module) {
  const { version } = syncVersion();
  console.log(`[version] synced v${version}`);
}

module.exports = {
  MAX_PATCH,
  parseVersion,
  formatVersion,
  bumpVersion,
  readVersionParts,
  writeVersionParts,
  syncVersion,
};
