import assert from 'node:assert/strict';
import { buildDiaryPages, diaryDescriptionLines, diaryImageId, diaryIdentity, DIARY_ORDER } from '../logic/spotlight-diary';
import type { GuideItem, WorkbookItemsBySection } from '../../../common/interfaces/guide.types';
import { buildPagesForDeckV2, buildV2MainList, V2_DECK_IDS } from '../logic/deck-builder-v2';
import { setActiveDestinationLocalize } from '../sync/destination-localize';
import { setSpotlightV3BuildContext, clearSpotlightV3BuildContext } from '../sync/spotlight-hook-source';
const image = (id: string) => '/assets/drive-file?id=' + id;
const item = (id: string, sectionKey: 'quan_an' | 'cafe'): GuideItem => ({ id, name: id, sectionKey, isPartner: true, imageUrl: image(id), imageSource: 'manual', diaryDescriptionRaw: 'View Đà Lạt đẹp\r\nQuán xinh\n\nQuán xinh', address: '07 Trần Quang Diệu' } as GuideItem);
const input = { destinationId: 'dalat', randomImages: ['r1','r2','r3'].map(image), hook: 'Hook chung', seed: 'test', itemsBySection: { quan_an: Array.from({length:4},(_,i)=>item('food'+i,'quan_an')), cafe: Array.from({length:3},(_,i)=>item('cafe'+i,'cafe')) } as WorkbookItemsBySection };
const pages = buildDiaryPages(input);
assert.equal(pages.length,10);
assert.deepEqual(pages.slice(3).map(p=>(p as any).items[0].sourceSectionKey),DIARY_ORDER);
assert.equal(new Set(pages.map(p=>diaryImageId(p.backgroundImage))).size,10);
assert.ok(pages.slice(3).every(p=>(p as any).items[0].isPartner));
assert.deepEqual(diaryDescriptionLines('View Đà Lạt đẹp\r\nQuán xinh\nQuán xinh\nMột câu. Hai câu'),['View Đà Lạt đẹp','Quán xinh']);
assert.throws(()=>buildDiaryPages({...input,destinationId:'greenland'}),/Đà Lạt/);
assert.throws(()=>buildDiaryPages({...input,randomImages:[]}),/Random/);
assert.throws(()=>buildDiaryPages({...input,itemsBySection:{...input.itemsBySection,cafe:input.itemsBySection.cafe.slice(0,2)}}),/Cafe/);
const usedLines = Object.fromEntries(pages.slice(3).map(p=>[diaryIdentity((p as any).items[0].name),[p.title]]));
const next=buildDiaryPages({...input,usedLines});
assert.ok(next.slice(3).every(p=>!usedLines[diaryIdentity((p as any).items[0].name)].includes(p.title)));
assert.deepEqual(diaryDescriptionLines('Ăn mì ngon\nBánh ngon lắm\nView đẹp. quán xinh\nView Đà Lạt đẹp'), ['View Đà Lạt đẹp']);
assert.equal(diaryIdentity('Đà Lạt'), diaryIdentity('da lat'));
const sharedRandom = buildDiaryPages({ ...input, randomImages: [...input.randomImages, image('food0')] });
assert.equal(new Set(sharedRandom.map(p => diaryImageId(p.backgroundImage))).size, 10);
assert.throws(() => buildDiaryPages({ ...input, itemsBySection: { ...input.itemsBySection, quan_an: input.itemsBySection.quan_an.slice(0,3) } }), /Quán ăn/);
assert.throws(() => buildDiaryPages({ ...input, itemsBySection: { ...input.itemsBySection, cafe: input.itemsBySection.cafe.map(p => ({ ...p, imageUrl: image('same') })) } }), /không trùng/);
assert.throws(() => buildDiaryPages({ ...input, itemsBySection: { ...input.itemsBySection, cafe: input.itemsBySection.cafe.map(p => ({ ...p, diaryImageUrls: [] })) } }), /Cafe/, 'Do not use name-matched library photos instead of Link_drive');
assert.ok(V2_DECK_IDS.includes('spotlight-v6-diary'));
setActiveDestinationLocalize('dalat'); setSpotlightV3BuildContext({ hooks: ['Hook kiểm thử'] });
const common = { itemsBySection: input.itemsBySection, imageUrls: [], libraryEntries: [], coverImageUrls: [], hinhNenImagePools: { default: [], green: [], dark: [], random: input.randomImages } };
assert.equal(buildV2MainList('spotlight-v6-diary', common)?.canvasPreset, 'tiktok-3x4');
assert.equal(buildV2MainList('spotlight-v6-diary', common)?.pages.length, 10);
setActiveDestinationLocalize('greenland');
assert.throws(() => buildPagesForDeckV2('spotlight-v6-diary', input.itemsBySection, [], [], 'test', undefined, undefined, [], common.hinhNenImagePools), /Đà Lạt/);
setActiveDestinationLocalize('dalat'); clearSpotlightV3BuildContext();
const coldPreview = buildV2MainList('spotlight-v6-diary', common);
assert.equal(coldPreview?.pages.length, 10, 'Cold-start preview must not depend on async hook warmup');
assert.ok(coldPreview?.pages[0].title.trim());
assert.throws(() => buildDiaryPages({ ...input, hook: '' }), /hook chung/, 'Generated lists must still reject missing hooks');
console.log('PASS diary core: 10 pages, 4/3 partners, distinct images, line boundaries, rotation and shortage errors.');
