import assert from 'node:assert/strict';
import { coverSourceId, prepareSpotlightDesign } from '../logic/spotlight-design';
import type { GuideDeckList } from '../../../common/interfaces/guide.types';
const base: GuideDeckList = { id:'spotlight-v2-caption-test', title:'Thử', navTitle:'Thử', description:'', pages:[{ type:'cover', title:'Đà Lạt', subtitle:'', backgroundImage:'/assets/drive-file?id=a' }] };
const pool = ['a','b','c','d','e'].map(id=>`/assets/drive-file?id=${id}`);
const labels = Object.fromEntries(['a','b','c','d','e'].map((id,i)=>[`drive:${id}`, {place:i<2?'same':id,topics:['green'],titlePlacement:'top-center' as const}]));
const copy = JSON.stringify(base);
const built = prepareSpotlightDesign(base,'spotlight-v2',pool,labels);
assert.equal(built.pages.length,1); assert.equal(new Set((built.pages[0] as any).coverImages).size,4);
assert.equal(built.coverReview?.warnings.length,0);
assert.equal(new Set((built.pages[0] as any).coverImages.map((u:string)=>labels[coverSourceId(u)].place)).size,4);
assert.equal(JSON.stringify(base),copy);
assert.deepEqual(prepareSpotlightDesign(base,'spotlight-v2',pool,labels),built);
const themed = {...base,pages:[{...base.pages[0], title:'Địa điểm xanh giữa rừng'}]};
assert.equal(prepareSpotlightDesign(themed,'spotlight-v4',pool,labels).coverReview?.warnings.length,0);
assert.ok(prepareSpotlightDesign(themed,'spotlight-v4',pool,{}).coverReview?.warnings.length);
assert.ok(prepareSpotlightDesign(base,'spotlight-v2',pool,{}).coverReview?.warnings.length);
assert.equal(prepareSpotlightDesign(base,'spotlight-v6',pool,labels),base);
assert.equal(prepareSpotlightDesign(base,'spotlight-v6-color-edit',pool,labels),base);
assert.equal(coverSourceId('/assets/drive-file?id=a&cache=123'),coverSourceId('https://drive.google.com/file/d/a/view'));
console.log('Spotlight design selection: PASS');
